CHROME_DRIVER_PATH = "D:\\posit-cloud-projet\\drivers\\chromedriver.exe"
USERNAME = "oded8909@hotmail.com"
PASSWORD = "PositTest1357"
SPACENAME = "My Test Space 1"
PROJECTNAME = "My Test Project 1"
CREATE_BTN = "/html/body/div/div/div/div[3]/div[1]/div[3]/div[1]/div[2]/a[2]"
